language: csharp
solution: USqlParser.sln
install:
  - nuget restore USqlParser.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release USqlParser.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./USqlParserTests/bin/Release/USqlParserTests.dll